<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(MeneesTargetNetCore)</TargetFramework>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Description>Portable database and storage contracts for Menees ChordBook.</Description>
	</PropertyGroup>
</Project>
